apiVersion: apps/vl 
kind: Deployment 
metadata:
 name: pv-deploy 
spec:
 replicas: 1
 selector:
   match Labels:
    app: mypv
 template:
   metadata:
    labels:
      app: mypv
   spec:
    containers:
    - name: shell
      image: centos:7
      command:
      - "bin/bash"
      - -c.1
      - "sleep 10000"
      volumeMounts:
      - name: mypd
        mountPath: "/tmp/persistent" 
    volumes:
    - name: mypd
      persistentVolumeClaim: 
        claimName: efs